import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/elements/header/header";

export const metadata: Metadata = {
  title: "Shadcn practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
      >
        <Header />
        <main className="pt-[75px]">
          {children}
        </main>

      </body>
    </html>
  );
}
